lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["json"]
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_user
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack
    get "/", UserController, :new
    resources "/message", MessageController
    resources "/users", UserController
    resources "/follows", FollowController
    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", MicroblogWeb do
    pipe_through :api
    
    resources "/likes", LikeController, except: [:new, :edit] 
  end
end

lib/microblog/user/message.ex
defmodule Microblog.User.Message do
  use Ecto.Schema
  import Ecto.Changeset
  alias Microblog.User.Message


  schema "message" do
    field :msg, :string
    field :name, :string
    field :user_id, :id

    timestamps()
  end

  @doc false
  def changeset(%Message{} = message, attrs) do
    message
    |> cast(attrs, [:name, :msg, :user_id])
    |> validate_required([:name, :msg])
  end
end

lib/microblog_web/controllers/message_controller.ex
defmodule MicroblogWeb.MessageController do
  use MicroblogWeb, :controller

  alias Microblog.User
  alias Microblog.User.Message

  def index(conn, _params) do
    message = User.list_messages()
    render(conn, "index.html", message: message)
  end

  def new(conn, _params) do
    changeset = User.change_message(%Message{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"message" => message_params}) do
    case User.create_message(message_params) do
      {:ok, message} ->
        MicroblogWeb.Endpoint.broadcast "updates:all", "new_msg",
           %{"message_name" => message.name,
             "message_date" => message.inserted_at,
             "message_user" => get_user(message.user_id).name,
             "user_show_path" => user_path(conn, :show, get_user(message.user_id)),
             "message_show_path" => message_path(conn, :show, message)}
        conn
        |> put_flash(:info, "Message created successfully.")
        |> redirect(to: message_path(conn, :show, message))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    message = User.get_message!(id)
    render(conn, "show.html", message: message)
  end

  def edit(conn, %{"id" => id}) do
    message = User.get_message!(id)
    changeset = User.change_message(message)
    render(conn, "edit.html", message: message, changeset: changeset)
  end

  def update(conn, %{"id" => id, "message" => message_params}) do
    message = User.get_message!(id)

    case User.update_message(message, message_params) do
      {:ok, message} ->
        conn
        |> put_flash(:info, "Message updated successfully.")
        |> redirect(to: message_path(conn, :show, message))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", message: message, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    message = User.get_message!(id)
    {:ok, _message} = User.delete_message(message)

    conn
    |> put_flash(:info, "Message deleted successfully.")
    |> redirect(to: message_path(conn, :index))
  end
end

lib/microblog_web/views/message_view.ex
defmodule MicroblogWeb.MessageView do
  use MicroblogWeb, :view

  def message_owner(message) do
    if message.user do
      message.user.email
    else
      "none"
    end
  end
end

lib/microblog_web/templates/message/edit.html.eex
<h2>Edit Message</h2>

<%= render "form.html", Map.put(assigns, :action, message_path(@conn, :update, @message)) %>

<div>
<%= link "Delete", to: message_path(@conn, :delete, @message), class: "btn btn-danger" %>
</div>

<span><%= link "Back", to: message_path(@conn, :show, @message) %></span>

lib/microblog_web/templates/message/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, "Title", class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, "Body", class: "control-label" %>
    <%= text_input f, :msg, class: "form-control" %>
    <%= error_tag f, :msg %>
  </div>

  <div class="form-group">
    <%= hidden_input f, :user_id, class: "form-control", value: @current_user.id %>
    <%= error_tag f, :user_id %>
  </div>

  <div class="form-group">
    <%= submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

lib/microblog_web/templates/message/index.html.eex
<div class="row pb-4">
  <div class="col">
  <h2>Discover messages...</h2>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Subject</th>
      <th>Date</th>
      <th>User</th>
    </tr>
  </thead>
  <tbody id="messages">
<%= for message <- Enum.reverse(@message) do %>
    <tr>
      <td><%= message.name %></td>
      <td><%= message.inserted_at %></td>
      <td><%= link get_user(message.user_id).name, to: user_path(@conn, :show, get_user(message.user_id)) %></td>
      <td class="text-right">
        <span>
          <%= link "Read More", to: message_path(@conn, :show, message), class: "btn btn-default btn-xs" %>
          <%= if @current_user &&  @current_user.is_admin? do %>
          <%= link "Delete", to: message_path(@conn, :delete, message), class: "btn btn-danger btn-xs" %>
          <% end %>
        </span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/microblog_web/templates/message/new.html.eex
<h2>New Message</h2>

<%= render "form.html", Map.put(assigns, :action, message_path(@conn, :create)) %>

<span><%= link "Back", to: message_path(@conn, :index) %></span>

lib/microblog_web/templates/message/show.html.eex
<div class="container mt-5 text-center">
  <div class="col">
      <h1 style="letter-spacing: 2px; text-transform: uppercase;">
        <b><%= @message.name %></b>
      </h1>
      <p><%= link get_user(@message.user_id).email, to: user_path(@conn, :show, @message.user_id) %> </p>
      <p>Date: <%= @message.inserted_at %></p>
      <hr>
      <p><%= @message.msg %></p>
  </div>
  <br>
   <div class="d-inline-block">
    <%= if @current_user do %>
    <div>
      <button id="like-add-button" class="btn btn-secondary"
         data-user-id="<%= @current_user.id %>">Like</button>
    </div>
    <% end %>
  </div>
 
  <div class="d-inline-block"> 
    <%= if @current_user && @current_user.id == @message.user_id do %>
    <%= link "Edit", to: message_path(@conn, :edit, @message), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div id="message-likes"
     data-path="<%= like_path(@conn, :index) %>"
     data-message_id="<%= @message.id %>">
  &nbsp;
</div>

<script id="likes-template" type="text/x-handlebars-template">
  <div class="text-center text-muted pt-5">
    {{#each data}}
    <p><b>{{user_email}}</b> likes this</p>
    {{else}}    
    <p>No likes yet. Be the first to like!</p>
    {{/each}}
  </div>
</script>