lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["json"]
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_user
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack
    get "/", UserController, :new
    resources "/message", MessageController
    resources "/users", UserController
    resources "/follows", FollowController
    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", MicroblogWeb do
    pipe_through :api
    
    resources "/likes", LikeController, except: [:new, :edit] 
  end
end

lib/microblog_web/views/layout_view.ex
defmodule MicroblogWeb.LayoutView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CatPerson</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>
  <body>
   <nav class="navbar navbar-dark bg-dark navbar-expand-md">
     <div class="container-fluid">
      <a class="navbar-brand" href="/">CatPerson</a>
      <button class="navbar-toggler" type="button"
              data-toggle="collapse" data-target="#main-navbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="main-navbar">
        <ul class="navbar-nav mr-auto">
         <%= if is_admin?(@current_user) do %>
            <li class="nav-item">
              <%= if String.contains?(to_string(@view_template), "index") do %>
              <% active = nav_active?(@conn, "users") %>
              <% end %>
              <%= link "Users", to: user_path(@conn, :index), class: "nav-link #{active}" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= if String.contains?(to_string(@view_template), "index") do %>
            <% active = nav_active?(@conn, "message") %>
            <% end %>
              <%= link "Explore", to: message_path(@conn, :index), class: "nav-link #{active}" %>
          </li>
          <%= if @current_user do %>
          <li class="nav-item">
            <% active = nav_active?(@conn, "follows") %>
	          <%= link "Follows", to: follow_path(@conn, :index), class: "nav-link #{active}" %>
          </li>
            <li class="nav-item">
              <% active = nav_active?(@conn, "users/" <> to_string(@current_user.id)) %>
              <%= link "My Profile", to: user_path(@conn, :show, @current_user), class: "nav-link #{active}" %>
            </li>
          <% end %>
        </ul>
      </div>

<%= if @current_user do %>
        <%= link "New Message", to: message_path(@conn, :new), class: "btn btn-primary mx-3" %>
        <span class="text-light">
          <%= @current_user.email %> |
          <%= link("Logout", to: session_path(@conn, :logout), method: :delete) %>
        </span>
      <% else %>
        <%= form_for @conn, session_path(@conn, :login),
              [as: "user", class: "form-inline w-75"], fn _f -> %>
          <input type="text" placeholder="email"
                 class="form-control" name="email">
          <input type="password" placeholder="password"
                 class="form-control" name="password">
          <input type="submit" value="Log in" class="btn btn-primary">
        <% end %>
      <% end %>
    </div>
   </nav>

    <div class="container">

      <div class="row">
        <div class="col-sm-12 my-2">
          <%= if get_flash(@conn, :info) do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error) do %>
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
          <% end %>
        </div>
      </div>
    </div>
      <main class="container" role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>